// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package couponlistthriftservice

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

// Attributes:
//  - ID
//  - Password
type UpdatePasswdRequestStruct struct {
  ID int32 `thrift:"id,1" db:"id" json:"id"`
  Password string `thrift:"password,2" db:"password" json:"password"`
}

func NewUpdatePasswdRequestStruct() *UpdatePasswdRequestStruct {
  return &UpdatePasswdRequestStruct{}
}


func (p *UpdatePasswdRequestStruct) GetID() int32 {
  return p.ID
}

func (p *UpdatePasswdRequestStruct) GetPassword() string {
  return p.Password
}
func (p *UpdatePasswdRequestStruct) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *UpdatePasswdRequestStruct)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.ID = v
}
  return nil
}

func (p *UpdatePasswdRequestStruct)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Password = v
}
  return nil
}

func (p *UpdatePasswdRequestStruct) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("UpdatePasswdRequestStruct"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *UpdatePasswdRequestStruct) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("id", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err) }
  if err := oprot.WriteI32(int32(p.ID)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err) }
  return err
}

func (p *UpdatePasswdRequestStruct) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("password", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:password: ", p), err) }
  if err := oprot.WriteString(string(p.Password)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.password (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:password: ", p), err) }
  return err
}

func (p *UpdatePasswdRequestStruct) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("UpdatePasswdRequestStruct(%+v)", *p)
}

// Attributes:
//  - Status
//  - Msg
type UpdatePasswdResponseStruct struct {
  Status int32 `thrift:"status,1" db:"status" json:"status"`
  Msg string `thrift:"msg,2" db:"msg" json:"msg"`
}

func NewUpdatePasswdResponseStruct() *UpdatePasswdResponseStruct {
  return &UpdatePasswdResponseStruct{}
}


func (p *UpdatePasswdResponseStruct) GetStatus() int32 {
  return p.Status
}

func (p *UpdatePasswdResponseStruct) GetMsg() string {
  return p.Msg
}
func (p *UpdatePasswdResponseStruct) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *UpdatePasswdResponseStruct)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI32(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  p.Status = v
}
  return nil
}

func (p *UpdatePasswdResponseStruct)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Msg = v
}
  return nil
}

func (p *UpdatePasswdResponseStruct) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("UpdatePasswdResponseStruct"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *UpdatePasswdResponseStruct) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("status", thrift.I32, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err) }
  if err := oprot.WriteI32(int32(p.Status)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err) }
  return err
}

func (p *UpdatePasswdResponseStruct) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("msg", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:msg: ", p), err) }
  if err := oprot.WriteString(string(p.Msg)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.msg (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:msg: ", p), err) }
  return err
}

func (p *UpdatePasswdResponseStruct) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("UpdatePasswdResponseStruct(%+v)", *p)
}

type UpdatePasswdThriftService interface {
  // Parameters:
  //  - RequestObj
  UpdatePasswd(requestObj *UpdatePasswdRequestStruct) (r *UpdatePasswdResponseStruct, err error)
}

type UpdatePasswdThriftServiceClient struct {
  Transport thrift.TTransport
  ProtocolFactory thrift.TProtocolFactory
  InputProtocol thrift.TProtocol
  OutputProtocol thrift.TProtocol
  SeqId int32
}

func NewUpdatePasswdThriftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UpdatePasswdThriftServiceClient {
  return &UpdatePasswdThriftServiceClient{Transport: t,
    ProtocolFactory: f,
    InputProtocol: f.GetProtocol(t),
    OutputProtocol: f.GetProtocol(t),
    SeqId: 0,
  }
}

func NewUpdatePasswdThriftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UpdatePasswdThriftServiceClient {
  return &UpdatePasswdThriftServiceClient{Transport: t,
    ProtocolFactory: nil,
    InputProtocol: iprot,
    OutputProtocol: oprot,
    SeqId: 0,
  }
}

// Parameters:
//  - RequestObj
func (p *UpdatePasswdThriftServiceClient) UpdatePasswd(requestObj *UpdatePasswdRequestStruct) (r *UpdatePasswdResponseStruct, err error) {
  if err = p.sendUpdatePasswd(requestObj); err != nil { return }
  return p.recvUpdatePasswd()
}

func (p *UpdatePasswdThriftServiceClient) sendUpdatePasswd(requestObj *UpdatePasswdRequestStruct)(err error) {
  oprot := p.OutputProtocol
  if oprot == nil {
    oprot = p.ProtocolFactory.GetProtocol(p.Transport)
    p.OutputProtocol = oprot
  }
  p.SeqId++
  if err = oprot.WriteMessageBegin("updatePasswd", thrift.CALL, p.SeqId); err != nil {
      return
  }
  args := UpdatePasswdThriftServiceUpdatePasswdArgs{
  RequestObj : requestObj,
  }
  if err = args.Write(oprot); err != nil {
      return
  }
  if err = oprot.WriteMessageEnd(); err != nil {
      return
  }
  return oprot.Flush()
}


func (p *UpdatePasswdThriftServiceClient) recvUpdatePasswd() (value *UpdatePasswdResponseStruct, err error) {
  iprot := p.InputProtocol
  if iprot == nil {
    iprot = p.ProtocolFactory.GetProtocol(p.Transport)
    p.InputProtocol = iprot
  }
  method, mTypeId, seqId, err := iprot.ReadMessageBegin()
  if err != nil {
    return
  }
  if method != "updatePasswd" {
    err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "updatePasswd failed: wrong method name")
    return
  }
  if p.SeqId != seqId {
    err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "updatePasswd failed: out of sequence response")
    return
  }
  if mTypeId == thrift.EXCEPTION {
    error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
    var error1 error
    error1, err = error0.Read(iprot)
    if err != nil {
      return
    }
    if err = iprot.ReadMessageEnd(); err != nil {
      return
    }
    err = error1
    return
  }
  if mTypeId != thrift.REPLY {
    err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "updatePasswd failed: invalid message type")
    return
  }
  result := UpdatePasswdThriftServiceUpdatePasswdResult{}
  if err = result.Read(iprot); err != nil {
    return
  }
  if err = iprot.ReadMessageEnd(); err != nil {
    return
  }
  value = result.GetSuccess()
  return
}


type UpdatePasswdThriftServiceProcessor struct {
  processorMap map[string]thrift.TProcessorFunction
  handler UpdatePasswdThriftService
}

func (p *UpdatePasswdThriftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
  p.processorMap[key] = processor
}

func (p *UpdatePasswdThriftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
  processor, ok = p.processorMap[key]
  return processor, ok
}

func (p *UpdatePasswdThriftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
  return p.processorMap
}

func NewUpdatePasswdThriftServiceProcessor(handler UpdatePasswdThriftService) *UpdatePasswdThriftServiceProcessor {

  self2 := &UpdatePasswdThriftServiceProcessor{handler:handler, processorMap:make(map[string]thrift.TProcessorFunction)}
  self2.processorMap["updatePasswd"] = &updatePasswdThriftServiceProcessorUpdatePasswd{handler:handler}
return self2
}

func (p *UpdatePasswdThriftServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  name, _, seqId, err := iprot.ReadMessageBegin()
  if err != nil { return false, err }
  if processor, ok := p.GetProcessorFunction(name); ok {
    return processor.Process(seqId, iprot, oprot)
  }
  iprot.Skip(thrift.STRUCT)
  iprot.ReadMessageEnd()
  x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function " + name)
  oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
  x3.Write(oprot)
  oprot.WriteMessageEnd()
  oprot.Flush()
  return false, x3

}

type updatePasswdThriftServiceProcessorUpdatePasswd struct {
  handler UpdatePasswdThriftService
}

func (p *updatePasswdThriftServiceProcessorUpdatePasswd) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
  args := UpdatePasswdThriftServiceUpdatePasswdArgs{}
  if err = args.Read(iprot); err != nil {
    iprot.ReadMessageEnd()
    x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
    oprot.WriteMessageBegin("updatePasswd", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return false, err
  }

  iprot.ReadMessageEnd()
  result := UpdatePasswdThriftServiceUpdatePasswdResult{}
var retval *UpdatePasswdResponseStruct
  var err2 error
  if retval, err2 = p.handler.UpdatePasswd(args.RequestObj); err2 != nil {
    x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing updatePasswd: " + err2.Error())
    oprot.WriteMessageBegin("updatePasswd", thrift.EXCEPTION, seqId)
    x.Write(oprot)
    oprot.WriteMessageEnd()
    oprot.Flush()
    return true, err2
  } else {
    result.Success = retval
}
  if err2 = oprot.WriteMessageBegin("updatePasswd", thrift.REPLY, seqId); err2 != nil {
    err = err2
  }
  if err2 = result.Write(oprot); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
    err = err2
  }
  if err2 = oprot.Flush(); err == nil && err2 != nil {
    err = err2
  }
  if err != nil {
    return
  }
  return true, err
}


// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - RequestObj
type UpdatePasswdThriftServiceUpdatePasswdArgs struct {
  RequestObj *UpdatePasswdRequestStruct `thrift:"requestObj,1" db:"requestObj" json:"requestObj"`
}

func NewUpdatePasswdThriftServiceUpdatePasswdArgs() *UpdatePasswdThriftServiceUpdatePasswdArgs {
  return &UpdatePasswdThriftServiceUpdatePasswdArgs{}
}

var UpdatePasswdThriftServiceUpdatePasswdArgs_RequestObj_DEFAULT *UpdatePasswdRequestStruct
func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) GetRequestObj() *UpdatePasswdRequestStruct {
  if !p.IsSetRequestObj() {
    return UpdatePasswdThriftServiceUpdatePasswdArgs_RequestObj_DEFAULT
  }
return p.RequestObj
}
func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) IsSetRequestObj() bool {
  return p.RequestObj != nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdArgs)  ReadField1(iprot thrift.TProtocol) error {
  p.RequestObj = &UpdatePasswdRequestStruct{}
  if err := p.RequestObj.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.RequestObj), err)
  }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("updatePasswd_args"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("requestObj", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:requestObj: ", p), err) }
  if err := p.RequestObj.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.RequestObj), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:requestObj: ", p), err) }
  return err
}

func (p *UpdatePasswdThriftServiceUpdatePasswdArgs) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("UpdatePasswdThriftServiceUpdatePasswdArgs(%+v)", *p)
}

// Attributes:
//  - Success
type UpdatePasswdThriftServiceUpdatePasswdResult struct {
  Success *UpdatePasswdResponseStruct `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewUpdatePasswdThriftServiceUpdatePasswdResult() *UpdatePasswdThriftServiceUpdatePasswdResult {
  return &UpdatePasswdThriftServiceUpdatePasswdResult{}
}

var UpdatePasswdThriftServiceUpdatePasswdResult_Success_DEFAULT *UpdatePasswdResponseStruct
func (p *UpdatePasswdThriftServiceUpdatePasswdResult) GetSuccess() *UpdatePasswdResponseStruct {
  if !p.IsSetSuccess() {
    return UpdatePasswdThriftServiceUpdatePasswdResult_Success_DEFAULT
  }
return p.Success
}
func (p *UpdatePasswdThriftServiceUpdatePasswdResult) IsSetSuccess() bool {
  return p.Success != nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdResult) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }


  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 0:
      if err := p.ReadField0(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdResult)  ReadField0(iprot thrift.TProtocol) error {
  p.Success = &UpdatePasswdResponseStruct{}
  if err := p.Success.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
  }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdResult) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("updatePasswd_result"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField0(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *UpdatePasswdThriftServiceUpdatePasswdResult) writeField0(oprot thrift.TProtocol) (err error) {
  if p.IsSetSuccess() {
    if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err) }
    if err := p.Success.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err) }
  }
  return err
}

func (p *UpdatePasswdThriftServiceUpdatePasswdResult) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("UpdatePasswdThriftServiceUpdatePasswdResult(%+v)", *p)
}


