// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package updateuserpasswword

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

// Attributes:
//  - ID
//  - NewPassword_
//  - OldPassword
type UpdateUserPasswWordRequestStruct struct {
	ID           int32  `thrift:"id,1" db:"id" json:"id"`
	NewPassword_ string `thrift:"newPassword,2" db:"newPassword" json:"newPassword"`
	OldPassword  string `thrift:"oldPassword,3" db:"oldPassword" json:"oldPassword"`
}

// func NewUpdateUserPasswWordRequestStruct() *UpdateUserPasswWordRequestStruct {
//   return &UpdateUserPasswWordRequestStruct{}
// }

func (p *UpdateUserPasswWordRequestStruct) GetID() int32 {
	return p.ID
}

func (p *UpdateUserPasswWordRequestStruct) GetNewPassword_() string {
	return p.NewPassword_
}

func (p *UpdateUserPasswWordRequestStruct) GetOldPassword() string {
	return p.OldPassword
}
func (p *UpdateUserPasswWordRequestStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserPasswWordRequestStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.ID = v
	}
	return nil
}

func (p *UpdateUserPasswWordRequestStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.NewPassword_ = v
	}
	return nil
}

func (p *UpdateUserPasswWordRequestStruct) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.OldPassword = v
	}
	return nil
}

func (p *UpdateUserPasswWordRequestStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UpdateUserPasswWordRequestStruct"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserPasswWordRequestStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("id", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:id: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.ID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:id: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordRequestStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("newPassword", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:newPassword: ", p), err)
	}
	if err := oprot.WriteString(string(p.NewPassword_)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.newPassword (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:newPassword: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordRequestStruct) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("oldPassword", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:oldPassword: ", p), err)
	}
	if err := oprot.WriteString(string(p.OldPassword)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.oldPassword (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:oldPassword: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordRequestStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserPasswWordRequestStruct(%+v)", *p)
}

// Attributes:
//  - Status
//  - Msg
type UpdateUserPasswWordResponseStruct struct {
	Status int32  `thrift:"status,1" db:"status" json:"status"`
	Msg    string `thrift:"msg,2" db:"msg" json:"msg"`
}

func NewUpdateUserPasswWordResponseStruct() *UpdateUserPasswWordResponseStruct {
	return &UpdateUserPasswWordResponseStruct{}
}

func (p *UpdateUserPasswWordResponseStruct) GetStatus() int32 {
	return p.Status
}

func (p *UpdateUserPasswWordResponseStruct) GetMsg() string {
	return p.Msg
}
func (p *UpdateUserPasswWordResponseStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserPasswWordResponseStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Status = v
	}
	return nil
}

func (p *UpdateUserPasswWordResponseStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Msg = v
	}
	return nil
}

func (p *UpdateUserPasswWordResponseStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UpdateUserPasswWordResponseStruct"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserPasswWordResponseStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("status", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.Status)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordResponseStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("msg", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:msg: ", p), err)
	}
	if err := oprot.WriteString(string(p.Msg)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.msg (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:msg: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordResponseStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserPasswWordResponseStruct(%+v)", *p)
}

type UpdateUserPasswWordThriftService interface {
	// Parameters:
	//  - RequestObj
	UpdateUserPasswWord(requestObj *UpdateUserPasswWordRequestStruct) (r *UpdateUserPasswWordResponseStruct, err error)
}

type UpdateUserPasswWordThriftServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewUpdateUserPasswWordThriftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UpdateUserPasswWordThriftServiceClient {
	return &UpdateUserPasswWordThriftServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewUpdateUserPasswWordThriftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UpdateUserPasswWordThriftServiceClient {
	return &UpdateUserPasswWordThriftServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - RequestObj
func (p *UpdateUserPasswWordThriftServiceClient) UpdateUserPasswWord(requestObj *UpdateUserPasswWordRequestStruct) (r *UpdateUserPasswWordResponseStruct, err error) {
	if err = p.sendUpdateUserPasswWord(requestObj); err != nil {
		return
	}
	return p.recvUpdateUserPasswWord()
}

func (p *UpdateUserPasswWordThriftServiceClient) sendUpdateUserPasswWord(requestObj *UpdateUserPasswWordRequestStruct) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("updateUserPasswWord", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs{
		RequestObj: requestObj,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *UpdateUserPasswWordThriftServiceClient) recvUpdateUserPasswWord() (value *UpdateUserPasswWordResponseStruct, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "updateUserPasswWord" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "updateUserPasswWord failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "updateUserPasswWord failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "updateUserPasswWord failed: invalid message type")
		return
	}
	result := UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type UpdateUserPasswWordThriftServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      UpdateUserPasswWordThriftService
}

func (p *UpdateUserPasswWordThriftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *UpdateUserPasswWordThriftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *UpdateUserPasswWordThriftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewUpdateUserPasswWordThriftServiceProcessor(handler UpdateUserPasswWordThriftService) *UpdateUserPasswWordThriftServiceProcessor {

	self2 := &UpdateUserPasswWordThriftServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["updateUserPasswWord"] = &updateUserPasswWordThriftServiceProcessorUpdateUserPasswWord{handler: handler}
	return self2
}

func (p *UpdateUserPasswWordThriftServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type updateUserPasswWordThriftServiceProcessorUpdateUserPasswWord struct {
	handler UpdateUserPasswWordThriftService
}

func (p *updateUserPasswWordThriftServiceProcessorUpdateUserPasswWord) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("updateUserPasswWord", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult{}
	var retval *UpdateUserPasswWordResponseStruct
	var err2 error
	if retval, err2 = p.handler.UpdateUserPasswWord(args.RequestObj); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing updateUserPasswWord: "+err2.Error())
		oprot.WriteMessageBegin("updateUserPasswWord", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("updateUserPasswWord", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - RequestObj
type UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs struct {
	RequestObj *UpdateUserPasswWordRequestStruct `thrift:"requestObj,1" db:"requestObj" json:"requestObj"`
}

func NewUpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs() *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs {
	return &UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs{}
}

var UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs_RequestObj_DEFAULT *UpdateUserPasswWordRequestStruct

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) GetRequestObj() *UpdateUserPasswWordRequestStruct {
	if !p.IsSetRequestObj() {
		return UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs_RequestObj_DEFAULT
	}
	return p.RequestObj
}
func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) IsSetRequestObj() bool {
	return p.RequestObj != nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) ReadField1(iprot thrift.TProtocol) error {
	p.RequestObj = &UpdateUserPasswWordRequestStruct{}
	if err := p.RequestObj.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.RequestObj), err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("updateUserPasswWord_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("requestObj", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:requestObj: ", p), err)
	}
	if err := p.RequestObj.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.RequestObj), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:requestObj: ", p), err)
	}
	return err
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserPasswWordThriftServiceUpdateUserPasswWordArgs(%+v)", *p)
}

// Attributes:
//  - Success
type UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult struct {
	Success *UpdateUserPasswWordResponseStruct `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewUpdateUserPasswWordThriftServiceUpdateUserPasswWordResult() *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult {
	return &UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult{}
}

var UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult_Success_DEFAULT *UpdateUserPasswWordResponseStruct

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) GetSuccess() *UpdateUserPasswWordResponseStruct {
	if !p.IsSetSuccess() {
		return UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &UpdateUserPasswWordResponseStruct{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("updateUserPasswWord_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserPasswWordThriftServiceUpdateUserPasswWordResult(%+v)", *p)
}
