// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package updateuserloginlogdetails

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

// Attributes:
//  - UserID
//  - LoginIP
//  - LoginStyle
//  - ChengHuiTongTraceLog
type UpdateUserLoginLogDetailsRequestStruct struct {
	UserID               int32  `thrift:"user_id,1" db:"user_id" json:"user_id"`
	LoginIP              string `thrift:"login_ip,2" db:"login_ip" json:"login_ip"`
	LoginStyle           int32  `thrift:"login_style,3" db:"login_style" json:"login_style"`
	ChengHuiTongTraceLog string `thrift:"chengHuiTongTraceLog,4" db:"chengHuiTongTraceLog" json:"chengHuiTongTraceLog"`
}

func NewLogUserlLoginRequestStruct() *UpdateUserLoginLogDetailsRequestStruct {
	return &UpdateUserLoginLogDetailsRequestStruct{}
}

func (p *UpdateUserLoginLogDetailsRequestStruct) GetUserID() int32 {
	return p.UserID
}

func (p *UpdateUserLoginLogDetailsRequestStruct) GetLoginIP() string {
	return p.LoginIP
}

func (p *UpdateUserLoginLogDetailsRequestStruct) GetLoginStyle() int32 {
	return p.LoginStyle
}

func (p *UpdateUserLoginLogDetailsRequestStruct) GetChengHuiTongTraceLog() string {
	return p.ChengHuiTongTraceLog
}
func (p *UpdateUserLoginLogDetailsRequestStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.UserID = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.LoginIP = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.LoginStyle = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.ChengHuiTongTraceLog = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UpdateUserLoginLogDetailsRequestStruct"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
		if err := p.writeField4(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsRequestStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("user_id", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:user_id: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.UserID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.user_id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:user_id: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsRequestStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("login_ip", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:login_ip: ", p), err)
	}
	if err := oprot.WriteString(string(p.LoginIP)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.login_ip (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:login_ip: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsRequestStruct) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("login_style", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:login_style: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.LoginStyle)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.login_style (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:login_style: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsRequestStruct) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("chengHuiTongTraceLog", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:chengHuiTongTraceLog: ", p), err)
	}
	if err := oprot.WriteString(string(p.ChengHuiTongTraceLog)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.chengHuiTongTraceLog (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:chengHuiTongTraceLog: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsRequestStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserLoginLogDetailsRequestStruct(%+v)", *p)
}

// Attributes:
//  - Status
//  - Msg
type UpdateUserLoginLogDetailsResponseStruct struct {
	Status int32  `thrift:"status,1" db:"status" json:"status"`
	Msg    string `thrift:"msg,2" db:"msg" json:"msg"`
}

func NewLogUserLoginResponseStruct() *UpdateUserLoginLogDetailsResponseStruct {
	return &UpdateUserLoginLogDetailsResponseStruct{}
}

func (p *UpdateUserLoginLogDetailsResponseStruct) GetStatus() int32 {
	return p.Status
}

func (p *UpdateUserLoginLogDetailsResponseStruct) GetMsg() string {
	return p.Msg
}
func (p *UpdateUserLoginLogDetailsResponseStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsResponseStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Status = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsResponseStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Msg = v
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsResponseStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UpdateUserLoginLogDetailsResponseStruct "); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsResponseStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("status", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.Status)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsResponseStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("msg", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:msg: ", p), err)
	}
	if err := oprot.WriteString(string(p.Msg)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.msg (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:msg: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsResponseStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserLoginLogDetailsResponseStruct (%+v)", *p)
}

type UpdateUserLoginLogDetailsThriftService interface {
	// Parameters:
	//  - RequestObj
	UpdateUserLoginLogDetails(requestObj *UpdateUserLoginLogDetailsRequestStruct) (r *UpdateUserLoginLogDetailsResponseStruct, err error)
}

type UpdateUserLoginLogDetailsThriftServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewUpdateUserLoginLogDetailsThriftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UpdateUserLoginLogDetailsThriftServiceClient {
	return &UpdateUserLoginLogDetailsThriftServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewUpdateUserLoginLogDetailsThriftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UpdateUserLoginLogDetailsThriftServiceClient {
	return &UpdateUserLoginLogDetailsThriftServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - RequestObj
func (p *UpdateUserLoginLogDetailsThriftServiceClient) UpdateUserLoginLogDetails(requestObj *UpdateUserLoginLogDetailsRequestStruct) (r *UpdateUserLoginLogDetailsResponseStruct, err error) {
	if err = p.sendupdateUserLoginLogDetails(requestObj); err != nil {
		return
	}
	return p.recvupdateUserLoginLogDetails()
}

func (p *UpdateUserLoginLogDetailsThriftServiceClient) sendupdateUserLoginLogDetails(requestObj *UpdateUserLoginLogDetailsRequestStruct) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("UpdateUserLoginLogDetails", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs{
		RequestObj: requestObj,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *UpdateUserLoginLogDetailsThriftServiceClient) recvupdateUserLoginLogDetails() (value *UpdateUserLoginLogDetailsResponseStruct, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "UpdateUserLoginLogDetails" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "UpdateUserLoginLogDetails failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "UpdateUserLoginLogDetails failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "UpdateUserLoginLogDetails failed: invalid message type")
		return
	}
	result := UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type UpdateUserLoginLogDetailsThriftServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      UpdateUserLoginLogDetailsThriftService
}

func (p *UpdateUserLoginLogDetailsThriftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *UpdateUserLoginLogDetailsThriftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *UpdateUserLoginLogDetailsThriftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewUpdateUserLoginLogDetailsThriftServiceProcessor(handler UpdateUserLoginLogDetailsThriftService) *UpdateUserLoginLogDetailsThriftServiceProcessor {

	self2 := &UpdateUserLoginLogDetailsThriftServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["UpdateUserLoginLogDetails"] = &UpdateUserLoginLogDetailsThriftServiceProcessorupdateUserLoginLogDetails{handler: handler}
	return self2
}

func (p *UpdateUserLoginLogDetailsThriftServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type UpdateUserLoginLogDetailsThriftServiceProcessorupdateUserLoginLogDetails struct {
	handler UpdateUserLoginLogDetailsThriftService
}

func (p *UpdateUserLoginLogDetailsThriftServiceProcessorupdateUserLoginLogDetails) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("UpdateUserLoginLogDetails", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult{}
	var retval *UpdateUserLoginLogDetailsResponseStruct
	var err2 error
	if retval, err2 = p.handler.UpdateUserLoginLogDetails(args.RequestObj); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing UpdateUserLoginLogDetails: "+err2.Error())
		oprot.WriteMessageBegin("UpdateUserLoginLogDetails", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("UpdateUserLoginLogDetails", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - RequestObj
type UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs struct {
	RequestObj *UpdateUserLoginLogDetailsRequestStruct `thrift:"requestObj,1" db:"requestObj" json:"requestObj"`
}

func NewUpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs() *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs {
	return &UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs{}
}

var UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs_RequestObj_DEFAULT *UpdateUserLoginLogDetailsRequestStruct

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) GetRequestObj() *UpdateUserLoginLogDetailsRequestStruct {
	if !p.IsSetRequestObj() {
		return UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs_RequestObj_DEFAULT
	}
	return p.RequestObj
}
func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) IsSetRequestObj() bool {
	return p.RequestObj != nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) ReadField1(iprot thrift.TProtocol) error {
	p.RequestObj = &UpdateUserLoginLogDetailsRequestStruct{}
	if err := p.RequestObj.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.RequestObj), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("updateUserLoginLogDetails_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("requestObj", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:requestObj: ", p), err)
	}
	if err := p.RequestObj.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.RequestObj), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:requestObj: ", p), err)
	}
	return err
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsArgs(%+v)", *p)
}

// Attributes:
//  - Success
type UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult struct {
	Success *UpdateUserLoginLogDetailsResponseStruct `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewUpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult() *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult {
	return &UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult{}
}

var UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult_Success_DEFAULT *UpdateUserLoginLogDetailsResponseStruct

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) GetSuccess() *UpdateUserLoginLogDetailsResponseStruct {
	if !p.IsSetSuccess() {
		return UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &UpdateUserLoginLogDetailsResponseStruct{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("updateUserLoginLogDetails_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserLoginLogDetailsThriftServiceupdateUserLoginLogDetailsResult(%+v)", *p)
}
