// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package usertendercoupondetails

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

// Attributes:
//  - UserId
//  - TenderId
//  - CouponId
//  - TenderMoney
//  - TimeLimit
//  - ChengHuiTongTraceLog
type UserTenderCouponDetailsRequestStruct struct {
	UserId               int32  `thrift:"userId,1" db:"userId" json:"userId"`
	TenderId             int32  `thrift:"tenderId,2" db:"tenderId" json:"tenderId"`
	CouponId             int32  `thrift:"couponId,3" db:"couponId" json:"couponId"`
	TenderMoney          string `thrift:"tenderMoney,4" db:"tenderMoney" json:"tenderMoney"`
	TimeLimit            int32  `thrift:"timeLimit,5" db:"timeLimit" json:"timeLimit"`
	ChengHuiTongTraceLog string `thrift:"chengHuiTongTraceLog,6" db:"chengHuiTongTraceLog" json:"chengHuiTongTraceLog"`
}

func NewUserTenderCouponDetailsRequestStruct() *UserTenderCouponDetailsRequestStruct {
	return &UserTenderCouponDetailsRequestStruct{}
}

func (p *UserTenderCouponDetailsRequestStruct) GetUserId() int32 {
	return p.UserId
}

func (p *UserTenderCouponDetailsRequestStruct) GetTenderId() int32 {
	return p.TenderId
}

func (p *UserTenderCouponDetailsRequestStruct) GetCouponId() int32 {
	return p.CouponId
}

func (p *UserTenderCouponDetailsRequestStruct) GetTenderMoney() string {
	return p.TenderMoney
}

func (p *UserTenderCouponDetailsRequestStruct) GetTimeLimit() int32 {
	return p.TimeLimit
}

func (p *UserTenderCouponDetailsRequestStruct) GetChengHuiTongTraceLog() string {
	return p.ChengHuiTongTraceLog
}
func (p *UserTenderCouponDetailsRequestStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.UserId = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.TenderId = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.CouponId = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.TenderMoney = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.TimeLimit = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.ChengHuiTongTraceLog = v
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UserTenderCouponDetailsRequestStruct"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
		if err := p.writeField4(oprot); err != nil {
			return err
		}
		if err := p.writeField5(oprot); err != nil {
			return err
		}
		if err := p.writeField6(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserTenderCouponDetailsRequestStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("userId", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:userId: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.UserId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.userId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:userId: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("tenderId", thrift.I32, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:tenderId: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.TenderId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.tenderId (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:tenderId: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("couponId", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:couponId: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.CouponId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.couponId (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:couponId: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("tenderMoney", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:tenderMoney: ", p), err)
	}
	if err := oprot.WriteString(string(p.TenderMoney)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.tenderMoney (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:tenderMoney: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) writeField5(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("timeLimit", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:timeLimit: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.TimeLimit)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.timeLimit (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:timeLimit: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) writeField6(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("chengHuiTongTraceLog", thrift.STRING, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:chengHuiTongTraceLog: ", p), err)
	}
	if err := oprot.WriteString(string(p.ChengHuiTongTraceLog)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.chengHuiTongTraceLog (6) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:chengHuiTongTraceLog: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsRequestStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserTenderCouponDetailsRequestStruct(%+v)", *p)
}

// Attributes:
//  - Status
//  - Coupon
//  - Msg
type UserTenderCouponDetailsResponseStruct struct {
	Status int32  `thrift:"status,1" db:"status" json:"status"`
	Coupon string `thrift:"coupon,2" db:"coupon" json:"coupon"`
	Msg    string `thrift:"msg,3" db:"msg" json:"msg"`
}

func NewUserTenderCouponDetailsResponseStruct() *UserTenderCouponDetailsResponseStruct {
	return &UserTenderCouponDetailsResponseStruct{}
}

func (p *UserTenderCouponDetailsResponseStruct) GetStatus() int32 {
	return p.Status
}

func (p *UserTenderCouponDetailsResponseStruct) GetCoupon() string {
	return p.Coupon
}

func (p *UserTenderCouponDetailsResponseStruct) GetMsg() string {
	return p.Msg
}
func (p *UserTenderCouponDetailsResponseStruct) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsResponseStruct) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Status = v
	}
	return nil
}

func (p *UserTenderCouponDetailsResponseStruct) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Coupon = v
	}
	return nil
}

func (p *UserTenderCouponDetailsResponseStruct) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Msg = v
	}
	return nil
}

func (p *UserTenderCouponDetailsResponseStruct) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("UserTenderCouponDetailsResponseStruct"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserTenderCouponDetailsResponseStruct) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("status", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:status: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.Status)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.status (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:status: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsResponseStruct) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("coupon", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:coupon: ", p), err)
	}
	if err := oprot.WriteString(string(p.Coupon)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.coupon (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:coupon: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsResponseStruct) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("msg", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:msg: ", p), err)
	}
	if err := oprot.WriteString(string(p.Msg)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.msg (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:msg: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsResponseStruct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserTenderCouponDetailsResponseStruct(%+v)", *p)
}

type UserTenderCouponDetailsThriftService interface {
	// Parameters:
	//  - RequestObj
	GetUserTenderCouponDetails(requestObj *UserTenderCouponDetailsRequestStruct) (r *UserTenderCouponDetailsResponseStruct, err error)
}

type UserTenderCouponDetailsThriftServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewUserTenderCouponDetailsThriftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserTenderCouponDetailsThriftServiceClient {
	return &UserTenderCouponDetailsThriftServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewUserTenderCouponDetailsThriftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserTenderCouponDetailsThriftServiceClient {
	return &UserTenderCouponDetailsThriftServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - RequestObj
func (p *UserTenderCouponDetailsThriftServiceClient) GetUserTenderCouponDetails(requestObj *UserTenderCouponDetailsRequestStruct) (r *UserTenderCouponDetailsResponseStruct, err error) {
	if err = p.sendGetUserTenderCouponDetails(requestObj); err != nil {
		return
	}
	return p.recvGetUserTenderCouponDetails()
}

func (p *UserTenderCouponDetailsThriftServiceClient) sendGetUserTenderCouponDetails(requestObj *UserTenderCouponDetailsRequestStruct) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("getUserTenderCouponDetails", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs{
		RequestObj: requestObj,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *UserTenderCouponDetailsThriftServiceClient) recvGetUserTenderCouponDetails() (value *UserTenderCouponDetailsResponseStruct, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "getUserTenderCouponDetails" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "getUserTenderCouponDetails failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "getUserTenderCouponDetails failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "getUserTenderCouponDetails failed: invalid message type")
		return
	}
	result := UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type UserTenderCouponDetailsThriftServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      UserTenderCouponDetailsThriftService
}

func (p *UserTenderCouponDetailsThriftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *UserTenderCouponDetailsThriftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *UserTenderCouponDetailsThriftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewUserTenderCouponDetailsThriftServiceProcessor(handler UserTenderCouponDetailsThriftService) *UserTenderCouponDetailsThriftServiceProcessor {

	self2 := &UserTenderCouponDetailsThriftServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["getUserTenderCouponDetails"] = &userTenderCouponDetailsThriftServiceProcessorGetUserTenderCouponDetails{handler: handler}
	return self2
}

func (p *UserTenderCouponDetailsThriftServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type userTenderCouponDetailsThriftServiceProcessorGetUserTenderCouponDetails struct {
	handler UserTenderCouponDetailsThriftService
}

func (p *userTenderCouponDetailsThriftServiceProcessorGetUserTenderCouponDetails) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("getUserTenderCouponDetails", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult{}
	var retval *UserTenderCouponDetailsResponseStruct
	var err2 error
	if retval, err2 = p.handler.GetUserTenderCouponDetails(args.RequestObj); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getUserTenderCouponDetails: "+err2.Error())
		oprot.WriteMessageBegin("getUserTenderCouponDetails", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("getUserTenderCouponDetails", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - RequestObj
type UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs struct {
	RequestObj *UserTenderCouponDetailsRequestStruct `thrift:"requestObj,1" db:"requestObj" json:"requestObj"`
}

func NewUserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs() *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs {
	return &UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs{}
}

var UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs_RequestObj_DEFAULT *UserTenderCouponDetailsRequestStruct

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) GetRequestObj() *UserTenderCouponDetailsRequestStruct {
	if !p.IsSetRequestObj() {
		return UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs_RequestObj_DEFAULT
	}
	return p.RequestObj
}
func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) IsSetRequestObj() bool {
	return p.RequestObj != nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) ReadField1(iprot thrift.TProtocol) error {
	p.RequestObj = &UserTenderCouponDetailsRequestStruct{}
	if err := p.RequestObj.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.RequestObj), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("getUserTenderCouponDetails_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("requestObj", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:requestObj: ", p), err)
	}
	if err := p.RequestObj.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.RequestObj), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:requestObj: ", p), err)
	}
	return err
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsArgs(%+v)", *p)
}

// Attributes:
//  - Success
type UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult struct {
	Success *UserTenderCouponDetailsResponseStruct `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewUserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult() *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult {
	return &UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult{}
}

var UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult_Success_DEFAULT *UserTenderCouponDetailsResponseStruct

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) GetSuccess() *UserTenderCouponDetailsResponseStruct {
	if !p.IsSetSuccess() {
		return UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &UserTenderCouponDetailsResponseStruct{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("getUserTenderCouponDetails_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserTenderCouponDetailsThriftServiceGetUserTenderCouponDetailsResult(%+v)", *p)
}
